/// <reference types="react" />
import Remarkable from "remarkable";
import { BaseComponent } from "react-vextensions";
import { ReplacementFunc } from "./VReactMarkdown";
declare type Props = {
    source: string;
    markdownOptions?: any;
    rendererOptions?: any;
    replacements?: {
        [key: string]: ReplacementFunc;
    };
    extraInfo?: any;
    containerType?: any;
    style?: any;
    addMarginsForDanglingNewLines?: boolean;
} & React.HTMLProps<HTMLDivElement>;
export declare class VReactMarkdown_Remarkable extends BaseComponent<Props, {}> {
    static defaultProps: {
        containerType: string;
    };
    markdown: Remarkable;
    InitMarkdown(props: any): void;
    ComponentWillReceiveProps(props: any): void;
    render(): import("react").ComponentElement<{
        style: any;
    }, import("react").Component<{
        style: any;
    }, any, any>> | import("react").DetailedReactHTMLElement<{
        style: any;
        children?: import("react").ReactNode;
        accept?: string;
        acceptCharset?: string;
        action?: string;
        allowFullScreen?: boolean;
        allowTransparency?: boolean;
        alt?: string;
        as?: string;
        async?: boolean;
        autoComplete?: string;
        autoFocus?: boolean;
        autoPlay?: boolean;
        capture?: string | boolean;
        cellPadding?: string | number;
        cellSpacing?: string | number;
        charSet?: string;
        challenge?: string;
        checked?: boolean;
        cite?: string;
        classID?: string;
        cols?: number;
        colSpan?: number;
        content?: string;
        controls?: boolean;
        coords?: string;
        crossOrigin?: string;
        data?: string;
        dateTime?: string;
        default?: boolean;
        defer?: boolean;
        disabled?: boolean;
        download?: any;
        encType?: string;
        form?: string;
        formAction?: string;
        formEncType?: string;
        formMethod?: string;
        formNoValidate?: boolean;
        formTarget?: string;
        frameBorder?: string | number;
        headers?: string;
        height?: string | number;
        high?: number;
        href?: string;
        hrefLang?: string;
        htmlFor?: string;
        httpEquiv?: string;
        integrity?: string;
        keyParams?: string;
        keyType?: string;
        kind?: string;
        label?: string;
        list?: string;
        loop?: boolean;
        low?: number;
        manifest?: string;
        marginHeight?: number;
        marginWidth?: number;
        max?: string | number;
        maxLength?: number;
        media?: string;
        mediaGroup?: string;
        method?: string;
        min?: string | number;
        minLength?: number;
        multiple?: boolean;
        muted?: boolean;
        name?: string;
        nonce?: string;
        noValidate?: boolean;
        open?: boolean;
        optimum?: number;
        pattern?: string;
        placeholder?: string;
        playsInline?: boolean;
        poster?: string;
        preload?: string;
        readOnly?: boolean;
        rel?: string;
        required?: boolean;
        reversed?: boolean;
        rows?: number;
        rowSpan?: number;
        sandbox?: string;
        scope?: string;
        scoped?: boolean;
        scrolling?: string;
        seamless?: boolean;
        selected?: boolean;
        shape?: string;
        size?: number;
        sizes?: string;
        span?: number;
        src?: string;
        srcDoc?: string;
        srcLang?: string;
        srcSet?: string;
        start?: number;
        step?: string | number;
        summary?: string;
        target?: string;
        type?: string;
        useMap?: string;
        value?: string | number | string[];
        width?: string | number;
        wmode?: string;
        wrap?: string;
        defaultChecked?: boolean;
        defaultValue?: string | string[];
        suppressContentEditableWarning?: boolean;
        suppressHydrationWarning?: boolean;
        accessKey?: string;
        className?: string;
        contentEditable?: boolean;
        contextMenu?: string;
        dir?: string;
        draggable?: boolean;
        hidden?: boolean;
        id?: string;
        lang?: string;
        slot?: string;
        spellCheck?: boolean;
        tabIndex?: number;
        title?: string;
        inputMode?: string;
        is?: string;
        radioGroup?: string;
        role?: string;
        about?: string;
        datatype?: string;
        inlist?: any;
        prefix?: string;
        property?: string;
        resource?: string;
        typeof?: string;
        vocab?: string;
        autoCapitalize?: string;
        autoCorrect?: string;
        autoSave?: string;
        color?: string;
        itemProp?: string;
        itemScope?: boolean;
        itemType?: string;
        itemID?: string;
        itemRef?: string;
        results?: number;
        security?: string;
        unselectable?: "on" | "off";
        'aria-activedescendant'?: string;
        'aria-atomic'?: boolean | "false" | "true";
        'aria-autocomplete'?: "none" | "both" | "inline" | "list";
        'aria-busy'?: boolean | "false" | "true";
        'aria-checked'?: boolean | "mixed" | "false" | "true";
        'aria-colcount'?: number;
        'aria-colindex'?: number;
        'aria-colspan'?: number;
        'aria-controls'?: string;
        'aria-current'?: boolean | "page" | "false" | "true" | "time" | "step" | "location" | "date";
        'aria-describedby'?: string;
        'aria-details'?: string;
        'aria-disabled'?: boolean | "false" | "true";
        'aria-dropeffect'?: "link" | "popup" | "none" | "copy" | "move" | "execute";
        'aria-errormessage'?: string;
        'aria-expanded'?: boolean | "false" | "true";
        'aria-flowto'?: string;
        'aria-grabbed'?: boolean | "false" | "true";
        'aria-haspopup'?: boolean | "grid" | "menu" | "listbox" | "false" | "true" | "dialog" | "tree";
        'aria-hidden'?: boolean | "false" | "true";
        'aria-invalid'?: boolean | "false" | "true" | "grammar" | "spelling";
        'aria-keyshortcuts'?: string;
        'aria-label'?: string;
        'aria-labelledby'?: string;
        'aria-level'?: number;
        'aria-live'?: "off" | "assertive" | "polite";
        'aria-modal'?: boolean | "false" | "true";
        'aria-multiline'?: boolean | "false" | "true";
        'aria-multiselectable'?: boolean | "false" | "true";
        'aria-orientation'?: "horizontal" | "vertical";
        'aria-owns'?: string;
        'aria-placeholder'?: string;
        'aria-posinset'?: number;
        'aria-pressed'?: boolean | "mixed" | "false" | "true";
        'aria-readonly'?: boolean | "false" | "true";
        'aria-relevant'?: "all" | "text" | "additions" | "additions text" | "removals";
        'aria-required'?: boolean | "false" | "true";
        'aria-roledescription'?: string;
        'aria-rowcount'?: number;
        'aria-rowindex'?: number;
        'aria-rowspan'?: number;
        'aria-selected'?: boolean | "false" | "true";
        'aria-setsize'?: number;
        'aria-sort'?: "none" | "ascending" | "descending" | "other";
        'aria-valuemax'?: number;
        'aria-valuemin'?: number;
        'aria-valuenow'?: number;
        'aria-valuetext'?: string;
        dangerouslySetInnerHTML?: {
            __html: string;
        };
        onCopy?: (event: import("react").ClipboardEvent<HTMLDivElement>) => void;
        onCopyCapture?: (event: import("react").ClipboardEvent<HTMLDivElement>) => void;
        onCut?: (event: import("react").ClipboardEvent<HTMLDivElement>) => void;
        onCutCapture?: (event: import("react").ClipboardEvent<HTMLDivElement>) => void;
        onPaste?: (event: import("react").ClipboardEvent<HTMLDivElement>) => void;
        onPasteCapture?: (event: import("react").ClipboardEvent<HTMLDivElement>) => void;
        onCompositionEnd?: (event: import("react").CompositionEvent<HTMLDivElement>) => void;
        onCompositionEndCapture?: (event: import("react").CompositionEvent<HTMLDivElement>) => void;
        onCompositionStart?: (event: import("react").CompositionEvent<HTMLDivElement>) => void;
        onCompositionStartCapture?: (event: import("react").CompositionEvent<HTMLDivElement>) => void;
        onCompositionUpdate?: (event: import("react").CompositionEvent<HTMLDivElement>) => void;
        onCompositionUpdateCapture?: (event: import("react").CompositionEvent<HTMLDivElement>) => void;
        onFocus?: (event: import("react").FocusEvent<HTMLDivElement>) => void;
        onFocusCapture?: (event: import("react").FocusEvent<HTMLDivElement>) => void;
        onBlur?: (event: import("react").FocusEvent<HTMLDivElement>) => void;
        onBlurCapture?: (event: import("react").FocusEvent<HTMLDivElement>) => void;
        onChange?: (event: import("react").FormEvent<HTMLDivElement>) => void;
        onChangeCapture?: (event: import("react").FormEvent<HTMLDivElement>) => void;
        onInput?: (event: import("react").FormEvent<HTMLDivElement>) => void;
        onInputCapture?: (event: import("react").FormEvent<HTMLDivElement>) => void;
        onReset?: (event: import("react").FormEvent<HTMLDivElement>) => void;
        onResetCapture?: (event: import("react").FormEvent<HTMLDivElement>) => void;
        onSubmit?: (event: import("react").FormEvent<HTMLDivElement>) => void;
        onSubmitCapture?: (event: import("react").FormEvent<HTMLDivElement>) => void;
        onInvalid?: (event: import("react").FormEvent<HTMLDivElement>) => void;
        onInvalidCapture?: (event: import("react").FormEvent<HTMLDivElement>) => void;
        onLoad?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onLoadCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onError?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onErrorCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onKeyDown?: (event: import("react").KeyboardEvent<HTMLDivElement>) => void;
        onKeyDownCapture?: (event: import("react").KeyboardEvent<HTMLDivElement>) => void;
        onKeyPress?: (event: import("react").KeyboardEvent<HTMLDivElement>) => void;
        onKeyPressCapture?: (event: import("react").KeyboardEvent<HTMLDivElement>) => void;
        onKeyUp?: (event: import("react").KeyboardEvent<HTMLDivElement>) => void;
        onKeyUpCapture?: (event: import("react").KeyboardEvent<HTMLDivElement>) => void;
        onAbort?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onAbortCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onCanPlay?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onCanPlayCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onCanPlayThrough?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onCanPlayThroughCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onDurationChange?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onDurationChangeCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onEmptied?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onEmptiedCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onEncrypted?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onEncryptedCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onEnded?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onEndedCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onLoadedData?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onLoadedDataCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onLoadedMetadata?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onLoadedMetadataCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onLoadStart?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onLoadStartCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onPause?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onPauseCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onPlay?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onPlayCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onPlaying?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onPlayingCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onProgress?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onProgressCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onRateChange?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onRateChangeCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onSeeked?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onSeekedCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onSeeking?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onSeekingCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onStalled?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onStalledCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onSuspend?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onSuspendCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onTimeUpdate?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onTimeUpdateCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onVolumeChange?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onVolumeChangeCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onWaiting?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onWaitingCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onClick?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onClickCapture?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onContextMenu?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onContextMenuCapture?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onDoubleClick?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onDoubleClickCapture?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onDrag?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDragCapture?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDragEnd?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDragEndCapture?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDragEnter?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDragEnterCapture?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDragExit?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDragExitCapture?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDragLeave?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDragLeaveCapture?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDragOver?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDragOverCapture?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDragStart?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDragStartCapture?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDrop?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onDropCapture?: (event: import("react").DragEvent<HTMLDivElement>) => void;
        onMouseDown?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onMouseDownCapture?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onMouseEnter?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onMouseLeave?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onMouseMove?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onMouseMoveCapture?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onMouseOut?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onMouseOutCapture?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onMouseOver?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onMouseOverCapture?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onMouseUp?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onMouseUpCapture?: (event: import("react").MouseEvent<HTMLDivElement>) => void;
        onSelect?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onSelectCapture?: (event: import("react").SyntheticEvent<HTMLDivElement>) => void;
        onTouchCancel?: (event: import("react").TouchEvent<HTMLDivElement>) => void;
        onTouchCancelCapture?: (event: import("react").TouchEvent<HTMLDivElement>) => void;
        onTouchEnd?: (event: import("react").TouchEvent<HTMLDivElement>) => void;
        onTouchEndCapture?: (event: import("react").TouchEvent<HTMLDivElement>) => void;
        onTouchMove?: (event: import("react").TouchEvent<HTMLDivElement>) => void;
        onTouchMoveCapture?: (event: import("react").TouchEvent<HTMLDivElement>) => void;
        onTouchStart?: (event: import("react").TouchEvent<HTMLDivElement>) => void;
        onTouchStartCapture?: (event: import("react").TouchEvent<HTMLDivElement>) => void;
        onPointerDown?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerDownCapture?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerMove?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerMoveCapture?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerUp?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerUpCapture?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerCancel?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerCancelCapture?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerEnter?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerEnterCapture?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerLeave?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerLeaveCapture?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerOver?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerOverCapture?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerOut?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onPointerOutCapture?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onGotPointerCapture?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onGotPointerCaptureCapture?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onLostPointerCapture?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onLostPointerCaptureCapture?: (event: import("react").PointerEvent<HTMLDivElement>) => void;
        onScroll?: (event: import("react").UIEvent<HTMLDivElement>) => void;
        onScrollCapture?: (event: import("react").UIEvent<HTMLDivElement>) => void;
        onWheel?: (event: import("react").WheelEvent<HTMLDivElement>) => void;
        onWheelCapture?: (event: import("react").WheelEvent<HTMLDivElement>) => void;
        onAnimationStart?: (event: import("react").AnimationEvent<HTMLDivElement>) => void;
        onAnimationStartCapture?: (event: import("react").AnimationEvent<HTMLDivElement>) => void;
        onAnimationEnd?: (event: import("react").AnimationEvent<HTMLDivElement>) => void;
        onAnimationEndCapture?: (event: import("react").AnimationEvent<HTMLDivElement>) => void;
        onAnimationIteration?: (event: import("react").AnimationEvent<HTMLDivElement>) => void;
        onAnimationIterationCapture?: (event: import("react").AnimationEvent<HTMLDivElement>) => void;
        onTransitionEnd?: (event: import("react").TransitionEvent<HTMLDivElement>) => void;
        onTransitionEndCapture?: (event: import("react").TransitionEvent<HTMLDivElement>) => void;
        ref?: import("react").LegacyRef<HTMLDivElement>;
        key?: string | number;
        m?: string | number;
        ml?: string | number;
        mr?: string | number;
        mt?: string | number;
        mb?: string | number;
        mlr?: string | number;
        mtb?: string | number;
        p?: string | number;
        pl?: string | number;
        pr?: string | number;
        pt?: string | number;
        pb?: string | number;
        plr?: string | number;
        ptb?: string | number;
        sel?: boolean;
        ct?: boolean;
        tabLabel?: string;
        active?: boolean;
        page?: any;
        match?: any;
    }, HTMLDivElement>;
}
export {};
